language: java
script: mvn test
addons:
   firefox: "46.0"
before_install:
 - "export DISPLAY=:99.0"
 - "export TRAVIS=true"
 - "sh -e /etc/init.d/xvfb start"
after_script:
- "sh -e /etc/init.d/xvfb stop"
jdk:
  - oraclejdk8
notifications:
  email:
    on_success: never
    on_failure: change

